// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"client/client","status":true,"description":"","parameters":{}},
{"name":"app/shelderevo","status":true,"description":"","parameters":{}}
];
